### ISSUE TITLE
New Inventory report type

### ISSUE THREAD

**Issue by FlaviaMS** [kjthoward/OMDC_Stock#10]
To streamline the process I thought you could create a new Inventory report accessible to all users that would contain only and all the information required for ordering.
This is:
* Supplier
* Catalogue number
* Name of product
* Project used in
* Ammount to order (so the minimum stock minus the ammount in stock)

As we mentioned before I think it is great if you automate the process in an e-mail but I think it is important to cover all possibilities to have it as an option on the database.

Hope it makes sense

Thanks

**Comment by kjthoward** [comment]
Ok, I'll add that report view next week and then work out how to automate the emails when it's deployed somewhere (as the automated task will be run by the server it's on, not the database itself)

**Comment by kjthoward** [comment]
Also, I assume that you only want items that can be ordered to be included on this list? So items that you make in house (solutions) don't show up on this list as it's for ordering

**Comment by FlaviaMS** [comment]
I think you are right on the first part, but your second paragraph does not make sense to me. Sorry

**Comment by kjthoward** [comment]
In the information you want you said you want "Project used in" to be included. But the project is linked to inventory item (when booked in) not reagent, whereas stock level (the thing that this report is ultimately checking) is tied to the reagent which does not have.

So it's very easy to say "This item should have 5 in stock but we have 3, therefor at least 2 need to be ordered", but it's currently impossible to say "This project should have 5 of this item in stock but we have 3, therefor at least 2 need to be ordered for this project".

Also did you mean to close this..?

**Comment by FlaviaMS** [comment]
No I did not mean to close it. 

Now I understood what you meant I think. But I don't think that is a massive issue, as if we have enough stock we can now borrow reagents and just update which project used what.

**Comment by kjthoward** [comment]
Ok, I've added a csv download with that data (except for project). For regular users it's on the tool bar, for Admins it's in the "Reports" dropdown

**Comment by FlaviaMS** [comment]
Is it possible to still have a project on the CSV? Even if it is tha last project that used it/the last project that was register at login on the database?

We don't need to keep track by Margaret will have to order with a project code? I still think this won't always work but I am sure Helene will ask for a project. (I will e-mail her what o did and ask anyways just in case.
