### ISSUE TITLE
For the Future

### ISSUE THREAD

**Issue by FlaviaMS** [kjthoward/OMDC_Stock#11]
THis is the future point that is not mentioned for this version of the database but I think it is cool so I wanted to share and the boss wants you to prepare for the future XD

In the future we would like to have the location of the reagents as a barcode too. Down to the box number X on the shelf number X of the fridge number X in room X.

Som eof this like general location is already duable in this version I believe. At least that is what I told the boss.

Let me know what you think.

**Comment by kjthoward** [comment]
Yes that is possible... It's easy to add things to the label file download. It would require a bit of work to store all the extra information, currently, it only stores one thing which is the room name. You could do it by just make a location called "Pre-PCR, Freezer X, Shelf 1" etc... but I think it would be much nicer to have them separated so you pick a room that then lists the possible freezers/fridges in that room and then it lists the shelves of the fridge/freezer.

So yes it is doable, but would need work which I won't start on yet until you want it
