### ISSUE TITLE
Problem with project edition

### ISSUE THREAD

**Issue by FlaviaMS** [kjthoward/OMDC_Stock#12]
The boss is predicting the future (a dark one) ahead of us.
So she loves that we put the project when we log a regent on the database, but she wants to be able (not forced) to edit this when we open the reagent.

This is because she says she wants to be able to lend reagents to other projects because of things like short expiry date and wants to keep track of this. 

Is this possible?

**Comment by kjthoward** [comment]
Yep, I can add a thing that when you are opening an item it comes up with the date opened (as it does now) but also a box for "Project used" or something, it will default to the current project so if you don't change anything it will be used by the project it was assigned at booking in. 

I assume if the project is changed that you want to keep both, so they'll be a "Bought by - <Project>" and then a "Used By - <Project>" on the items sumary page?

**Comment by FlaviaMS** [comment]
Yes I think ideally would want to keep information on both to keep a paper trail of who owes who and what is owed.
