### ISSUE TITLE
A question - as I am confused

### ISSUE THREAD

**Issue by FlaviaMS** [kjthoward/OMDC_Stock#13]
When we don't do this face to face my brain gets lost...

I have noticed that I can now change to project when I open reagents. But which report should I choose to monitor these changes?

**Comment by kjthoward** [comment]
Currently, Inventory reports and Stock Reports list both "Project" and "Used by Project". 

Project reports list all items that were booked in for that project but also show the project that used each item.

**Comment by FlaviaMS** [comment]
That is perfect. I will add this to the SOP and then close it.
