### ISSUE TITLE
Minimum number of items in stock

### ISSUE THREAD

**Issue by FlaviaMS** [kjthoward/OMDC_Stock#17]
There is a question on if it would eb possible to add half numbers to the minimum number required by the stock database?
I would assume that the people woould need to open half a kit at a time. Do you think that is feasable?

**Comment by kjthoward** [comment]
I don't really see the point...? You can't open half of something, it's either open or it's not. Even if you open a kit to take just one reagent (e.g opening another extraction kit just to use some buffer), the kit box itself has been open and should be marked as such. Or if there is a case where there are two distinct items (e.g a miseq sequencing kit, which comes in two parts) and you can use a flow cell but a different cartridge not from that same "kit" then they should be entered onto the database as two items.

If you have a good reason to do it can be done (but it would require a database reset as you'd be changing an integer field to a decimal field), but it'd also add an extra step to opening things as you'd need to specify how much of the item you've opened...

**Comment by FlaviaMS** [comment]
You make a very good point. Feel free to close it and leave the database as it is.
Thanks
