### ISSUE TITLE
E-mail on discarded stock

### ISSUE THREAD

**Issue by FlaviaMS** [kjthoward/OMDC_Stock#18]
I have receive this e-mail.

![image](https://user-images.githubusercontent.com/65717277/87922894-82efeb80-ca74-11ea-8978-d6073ee6d4b7.png)

I am just wondering tehreason for getting teh e-mail. IS it because the item was nto validated?

If so, is it possible to turn off this option? We will be using a lot of things without validation and it will become a pain to receive all of those e-mails.

**Comment by kjthoward** [comment]
Yes, if you discard an item without it being validated you get an email, this was something that ORGL wanted so they could keep track of people discarding items without them being used/validated (as the only reason to throw away unvalidated items is that they expired, they wanted to track how much wastage there was).

It's easy for me to disable it if you want but do you want it permanently disabled, or just for now at the start when you're entering things for the first time?

**Comment by FlaviaMS** [comment]
That makes a lot of sense and it was what I have assumed. 
Now that I know you can easily disable it I will check with Helene what she rpefer to "validate" an item and write N/A if no real validation was done or tho dispose of it like I did.

Thanks

**Comment by FlaviaMS** [comment]
Ok Helene has decided to leave as it is. We will be validateing items with N/A if needed.

Thanks for the help. I will clsoe this down.
