### ISSUE TITLE
Mandatory fields identification

### ISSUE THREAD

**Issue by FlaviaMS** [kjthoward/OMDC_Stock#2]
Is it possible to identify which fields are mandatory when booking a new inventory item or recipe?
Maybe just add an * or something.

**Comment by kjthoward** [comment]
Do you want it just on the "booking in" items pages? I can add a "*" to every field on every form thats required if that's better

**Comment by FlaviaMS** [comment]
If it is easy enough I think It can make it more user friendly. It is the most useful in the booking in pages though, so if it much work its ok to leave it

**Comment by kjthoward** [comment]
Was easy enough to just add it to the overall form template, so it applies to every form.

Closed by commit fcb19269aca23936f626765327c024bf1d420186
