### ISSUE TITLE
Item validation

### ISSUE THREAD

**Issue by FlaviaMS** [kjthoward/OMDC_Stock#21]
This is something we might have discussed, but I can't remember.
When I validate one item does the whole batch get validated (same lot number and date received)?

**Comment by kjthoward** [comment]
For solutions, it is just that one item. For regular items it's ever item with the same lot number, date recieved doesn't matter (I did bring that up to regional and they didn't seem to care... but I can easily make it check the date recieved too)

**Comment by FlaviaMS** [comment]
If you think it is an easy enough change for you we would prefer to have it as lot number AND as date received.
