### ISSUE TITLE
Centre titles and straight lines

### ISSUE THREAD

**Issue by FlaviaMS** [kjthoward/OMDC_Stock#27]
Helene kindly requests (and we do not expect you to do it) if the title on the PDF report can be centres and if o the main item pages the columns could be align in straight lines, not just on the left side.
Not sure how to explain this better so I made some stuff on paint.

Now: 
![image](https://user-images.githubusercontent.com/65717277/88536058-01173980-d003-11ea-9a08-f1891143eb6b.png)

In Helene's ideal world
![image](https://user-images.githubusercontent.com/65717277/88536193-45a2d500-d003-11ea-8c17-14ae4401493e.png)

**Comment by kjthoward** [comment]
Title on the pdf reports I can possibly do... I did try to get that working for a while but had no luck, but I can try again.

I'm not sure putting the item names into columns like that looks any better/is more readible... but I can have a look

**Comment by kjthoward** [comment]
How does this look?

![image](https://user-images.githubusercontent.com/40895027/88560020-7ac01f00-d025-11ea-93d0-25b9f6905512.png)

**Comment by FlaviaMS** [comment]
I assume that is what she meant, so very good
