### ISSUE TITLE
Minimum stock level

### ISSUE THREAD

**Issue by FlaviaMS** [kjthoward/OMDC_Stock#3]
To make it a bit full proof can you add the message "if the volume of the item is tracked, stock numbers are in ul" because having 1 box or 1 ul is very different

**Comment by kjthoward** [comment]
Where/What page(s) do you want this message to be on??

**Comment by FlaviaMS** [comment]
I think it would be the most helpful in the page to add a new reagent (on the admin version)

**Comment by kjthoward** [comment]
Was easy enough to just add it to the overall form template, so it applies to every form.

Closed by commit [fcb19269aca23936f626765327c024bf1d420186](https://github.com/kjthoward/OMDC_Stock/commit/fcb19269aca23936f626765327c024bf1d420186)

**Comment by kjthoward** [comment]
Like this? 
![image](https://user-images.githubusercontent.com/40895027/82567150-e2b13f80-9b74-11ea-85e5-0b91c2551b05.png)

**Comment by FlaviaMS** [comment]
Yes sir, it look much more Flavia proof =D
