### ISSUE TITLE
Suggestion for search page

### ISSUE THREAD

**Issue by FlaviaMS** [kjthoward/OMDC_Stock#31]
![image](https://user-images.githubusercontent.com/65717277/89321344-c3598700-d67a-11ea-86d5-15c8ce3f1d6e.png)

There is a request to add PO number as a "searchable" field on the search page.
Is this easy to do?

**Comment by kjthoward** [comment]
Yes that's quite easy to do, I can sort that out tomorrow morning.

**Comment by FlaviaMS** [comment]
Awesome. Daisy says you are a "star". Don't forget to polish your halo (also by Daisy)

**Comment by kjthoward** [comment]
Do you want the search to be exact or partial?? So if you have two items, one with PO "0" and another with "00000" if you search for "0" exact matching will only return then one that is "0" whereas partial will return both since both contain "0".

**Comment by FlaviaMS** [comment]
We think partial is best. THanks for checking. I doid not even consider that
