### ISSUE TITLE
Remove deactivated projects

### ISSUE THREAD

**Issue by FlaviaMS** [kjthoward/OMDC_Stock#32]
Hey,

Can you make it that deactivated stuff is not possible to be selected anymore. It hapenned again today that I misspelled Head in thehead and neck project.
Now both the wrong and the correct projects appear. I fear this might cause a lot more confusion and some people will select the wrong one.

Thanks

**Comment by kjthoward** [comment]
Where can you still see the deactivated project? I just checked and on the booking in page deactivated projects don't show up in the list

**Comment by FlaviaMS** [comment]
I can see it on the opening item page.
![image](https://user-images.githubusercontent.com/65717277/91417243-65b6f580-e848-11ea-9b14-463418a7c0b1.png)
