### ISSUE TITLE
Dates missing issue on users

### ISSUE THREAD

**Issue by FlaviaMS** [kjthoward/OMDC_Stock#38]
Hey for some reason the way the date is presented for me and for teh users (Daniella specifically) is different.
On top of that when Daniella was filling the expiry date it would ot show days beofre the 5th. I think because today is the fith. But it would not show them as a possibility for any month.

**Comment by kjthoward** [comment]
What do you mean it shows dates differently...? How are the dates different, do you have any screenshots etc..?

What item was Daniella booking in and do you have pictures of the dates not working etc..? I need more info about what wasn't working to try and figure out why it wasn't working.

What browser was she using? I just tried with both Firefox and Chrome and the Expiry date when booking in items works as it should do. The expiry date when you are booking in items won't let you pick a date that is before the date received (this is dynamic, so if you change the date received the calendar widget will update to block all dates before whatever you set the date received to be) it's not specifically to do with "today"

**Comment by FlaviaMS** [comment]
The top figure is mine and the bottom is daniella's.Somehow this time the days all appear on Daniell's dataabse, but it still look different.
P.S sorry for teh quality but for Daniell's I took a picture on my phone. 


![image](https://user-images.githubusercontent.com/65717277/98272740-527f7f00-1f89-11eb-9409-264a66928999.png)

![image](https://user-images.githubusercontent.com/65717277/98273378-17ca1680-1f8a-11eb-8919-4ded40cec795.png)

**Comment by kjthoward** [comment]
What web browser is she (and anyone else that has this issue) using??

**Comment by kjthoward** [comment]
Closing this as it seemed to have been fixed by changing to a more up to date browser. If you get the issue again feel free to re-open with more information, including the web browser that was being used.

**Comment by FlaviaMS** [comment]
I discussed with Daniella the problem and she has not reported any issues since. Will keep it in mind.
