### ISSUE TITLE
Change item location

### ISSUE THREAD

**Issue by FlaviaMS** [kjthoward/OMDC_Stock#39]
I was wondering if you could make the location of an item something that an Admin could edit. ??
When I edit inventory data only lets's me change things regarding to open,validate and close an item.
Due to tight space in the lab we store things in many places and move them around so it would be nice to be able to edit that.

**Comment by kjthoward** [comment]
Ok, what about this:

Under "Edit Item", on that page the storage location will be a hyperlink which takes you to page to select a new Storage location:

![image](https://user-images.githubusercontent.com/40895027/99825619-2bab7600-2b4f-11eb-87f1-e0cc7aaedead.png)

Selecting a new location gives you this message:

![image](https://user-images.githubusercontent.com/40895027/99826122-d6239900-2b4f-11eb-8faf-7348c6db3061.png)

With an error if you select the same location:

![image](https://user-images.githubusercontent.com/40895027/99826179-eb002c80-2b4f-11eb-8301-f94deca0b78e.png)

**Comment by FlaviaMS** [comment]
I think should be great! Thanks
