### ISSUE TITLE
CSV files for labels

### ISSUE THREAD

**Issue by FlaviaMS** [kjthoward/OMDC_Stock#4]
For some reason the brady software now seems to prefer if we have a first line with headers. Is it ok/fast and easy to update this only after we receive the printer so I know exactly which software it comes with?

**Comment by kjthoward** [comment]
Yep, very easy to change what the csv download file contains

**Comment by FlaviaMS** [comment]
I finally only have access to the lite version and there are three changes that we need you to do to streamline the process.

1 - Change the file format to .xlsx

2- Add the date that the item was booked in. This is partially because of the software and partially because it might be good practice to have the data booked in and not the automatic date I had which was the date the labels were made.

3 - If it is not much trouble, could you change the order of the columns on the file and put stock number last. the order of the other three does not matter much, but having barcode at the end would help.

Unfortunately, my computer is activist differently from the lab one when it comes to the header.
I will update you from the lab when I can, but I still have two weeks of the trial software on the work PC, so worst case scenario in two weeks the header situation might change.
Ideally I would want to finalise this before then, and only change it if absolutely needed.

**Comment by FlaviaMS** [comment]
I seem to have an issue with the date thing =/

On the excel column I only see date, but on Brady it comes up with time too and that means its too big for the label.

![image](https://user-images.githubusercontent.com/65717277/83872734-757fdb80-a72a-11ea-81e5-b65f17381d9b.png)

![image](https://user-images.githubusercontent.com/65717277/83872758-84668e00-a72a-11ea-8da3-a66c30fb7d30.png)


Can you think of why that is? Is is just a Brady problem?

**Comment by kjthoward** [comment]
Not sure exactly...

Could you try opening the Excel file and then saving the worksheet and try opening it in Brady. If that has no change try selecting the date cell and changing the type to "Short date"
![image](https://user-images.githubusercontent.com/40895027/83883860-fabfbc00-a73b-11ea-8711-c08a78ed3230.png)
Then saving the worksheet and try opening it in Brady.

It might also be a setting in your label template, can you set the datatype of the field to be "date" or something??

**Comment by FlaviaMS** [comment]
None of the options you gave help. I might just get you to take it out then and not have it at all on the labels.

Thanks for trying and sorry to make you change it again.
