### ISSUE TITLE
Expired items

### ISSUE THREAD

**Issue by FlaviaMS** [kjthoward/OMDC_Stock#40]
I understand this might be a strange request but due to the level of desorganisation within the department I think it could be useful to have a report generating menu for expired items. I have been fiding some by chance and I have no clue where they are as they have been used.
Could you make such a thing?

**Comment by kjthoward** [comment]
So if you go to Reports > Inventory reports and then select "Items expiring soon" That shows you all items that are expiring within 4 weeks, and items that have already expired. But if you want I can just add another dropdown to that to show only items that are actually expired.

**Comment by kjthoward** [comment]
Closed as "Items Expiring Soon" report can be used instead
