### ISSUE TITLE
Suggestion/Request

### ISSUE THREAD

**Issue by FlaviaMS** [kjthoward/OMDC_Stock#45]
Is it possible to add to the menu "Reports" a sub menu of "All In-Stock item" to the users? We have it only for admns but it would be helpfull if the girls can download it to do monthly stock check.

Please let me know if thre is a reason why it is not available for users.

Thanks

**Comment by kjthoward** [comment]
Probably because for the Churchill they wanted them seperate.

Do you want them to have access to all reports (inventory Reports, Stock Reports, Project reports and items to order), or just add that one specific report?

**Comment by FlaviaMS** [comment]
Thanks =D
