### ISSUE TITLE
Edit recipes

### ISSUE THREAD

**Issue by FlaviaMS** [kjthoward/OMDC_Stock#46]
Hey,

Could we add an option do edit ("activete/deactivate) recipes?

Thanks,
Flavia

**Comment by kjthoward** [comment]
This already exists. Recipes, after being made, are treated basically the same as regular reagents, meaning they can also be (de)activated using the "(De)Activate Reagents" section under "Edit Data"

**Comment by FlaviaMS** [comment]
Correct but somehow they still appear in teh recipe tab. Could this be removed?
