### ISSUE TITLE
Using database before AWS

### ISSUE THREAD

**Issue by FlaviaMS** [kjthoward/OMDC_Stock#5]
Helen is looking into the process of uploading the database on AWS. My question comes from the fact that I know this will take a long time.
Can we use the database routinely and then move it to AWS with the whole stock?

**Comment by kjthoward** [comment]
Yes that should be fine. The database code can be pulled straight from GitHub into AWS and then we'll just have to manually upload the database file to AWS from wherever it's currently running

**Comment by FlaviaMS** [comment]
Ok, pretend I am 5 on top of the fact that I don't speak computer. Just to make sure, the database file will contain all of the stock we upload on it right? including finished things?

**Comment by kjthoward** [comment]
Yes. The database file contains all the information (reagents, recipes, suppliers, user logins etc...) and the code is what interacts with the database (puts in information, retrieves and displays information etc...).
