### ISSUE TITLE
Account requirements

### ISSUE THREAD

**Issue by FlaviaMS** [kjthoward/OMDC_Stock#9]
I thought we had discussed before that we could have accounts without an e-mail linked to them.
Is that not true anymore?

I don't think we need them. I am just asking because, currently, the only way to recover a password is by getting the user name I can't as a user change anyone's password. Which is fine I am just making sure it is on purpose.

I assume changing user names is not possible right?
Just asking due to situations like Sarah Taylor vs Sarah Pericli. Would I have to create a new user for the person if they insist changing something?

**Comment by kjthoward** [comment]
Emails are not required.

The only way a user can reset their own password is if the account has an email address, however any admin can reset an accounts password back to "stockdb1" (which must be changed the next time that person logs in). To reset someones password:

- Go to the "Update Users" page
- Select the username you want to reset
- At the top of the page there is a section that looks like this:
![image](https://user-images.githubusercontent.com/40895027/83869019-c6d89c80-a723-11ea-9bf7-102cece5b2be.png)
- Click the hyperlink that says "this form"
- Then click the "RESET PASSWORD" button

Regular Admins can not change usernames, the only people who can do this are superusers (which I imagine will be just me for now). If someone really wants their username changed I, or anyone else who gets made a superuser, can change it. Or if you want I can just remove that restriction so any Admin can change usernames.

**Comment by FlaviaMS** [comment]
Thanks for the reset Password thing. I will add this to the SOP.

Regarding the usernames. If you think technically speaking it would be ok to allow admins to do it I would prefer it. That way we would have to bother you less.
